include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    invalid_annotation_target: ignore
    unreachable_switch_default: ignore
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "lib/config/keys.dart"

linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - avoid_print
    - sort_constructors_first
    - unnecessary_lambdas
    - use_super_parameters
